pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Build and Test (8, 8/sdk/windowsservercore-ltsc2019/Dockerfile, windows)
      - status-success=Build and Test (11, 8/sdk/windowsservercore-ltsc2019/Dockerfile, windows)
    actions:
      merge:
        method: squash